sudo: required
services:
  - docker

before_install:
  - docker build -t shil.ydv@gmail.com/docker-react -f Dockerfile.dev .

script:
  - docker run shil.ydv@gmail.com/docker-react npm run test -- --coverage
